spring.application.name=demo

# Web Server Port
server.port=8080

# TCP Server Port [cite: 3, 8]
tcp.port=9090

# Remote HTTP Endpoint [cite: 4, 8]
http.endpoint=http://api.destination.com/metrics

# Enable Virtual Threads for Java 21 efficiency
spring.threads.virtual.enabled=true
